apiVersion: v1
kind: Secret
metadata:
  name: postgres-overlay-secret
  namespace: tap-install
stringData:
  patch.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Postgres"}), expects="0+"
    ---
    spec:
      #@overlay/match missing_ok=True 
      #@overlay/remove
      resources:
