apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: petclinic-gateway
  namespace: default
spec:
  count: 1
  host: petclinic.gkelab4.tap.fynesy.com
  api:
    serverUrl: petclinic.gkelab4.tap.fynesy.com
    title: Tanzu PetClinic APIs
    description: PetClinic with SCG Demo
    version: 0.0.1
    groupId: "petclinic"
    cors:
      allowedOrigins:
      - "https://api-portal.gkelab4.tap.fynesy.com"